### ISSUE TITLE
Model required for Mask Ops nodes

### ISSUE THREAD

**Issue by hben35096** [ManglerFTW/ComfyI2I#10]
Can I download the models required by the Mask Ops node manually? If downloaded manually, does it have a designated storage folder?

**Comment by hben35096** [comment]
Prompt executed in 20.29 seconds
Downloading pytorch_model.bin:   0%|          | 0.00/603M [00:16<?, ?B/s]
got prompt
Downloading pytorch_model.bin:   0%|          | 947k/603M [00:04<50:17, 200kB/s]!!! Exception during processing !!!
Traceback (most recent call last):
  File "/mnt/workspace/ComfyUI/execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/mnt/workspace/ComfyUI/execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/mnt/workspace/ComfyUI/execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/mnt/workspace/ComfyUI/custom_nodes/ComfyI2I/ComfyI2I.py", line 1068, in Mask_Ops
    model = CLIPSegForImageSegmentation.from_pretrained(model, cache_dir=cache)
  File "/opt/conda/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2222, in from_pretrained
    resolved_archive_file = cached_file(
  File "/opt/conda/lib/python3.10/site-packages/transformers/utils/hub.py", line 409, in cached_file
    resolved_file = hf_hub_download(
  File "/opt/conda/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1364, in hf_hub_download
    http_get(
  File "/opt/conda/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 547, in http_get
    raise EnvironmentError(
OSError: Consistency check failed: file should be of size 603143713 but has size 946945 (pytorch_model.bin).
We are sorry for the inconvenience. Please retry download and pass `force_download=True, resume_download=False` as argument.
If the issue persists, please let us know by opening an issue on https://github.com/huggingface/huggingface_hub.

Prompt executed in 9.05 seconds
Downloading pytorch_model.bin:   0%|          | 947k/603M [00:04<52:22, 192kB/s]


The download keeps failing

**Comment by ManglerFTW** [comment]
Hey,

That is the ClipSeg model. It would need to go in '\ComfyUI\models\clipseg\'.

**Comment by hben35096** [comment]
> Hey,
> 
> That is the ClipSeg model. It would need to go in '\ComfyUI\models\clipseg'.
Thank you, I put the file in:
ComfyUI/models/clipseg/models--CIDAS--clipseg-rd64-refined/snapshots/583b388deb98a04feb3e1f816dcdb8f3062ee205
