### ISSUE TITLE
RuntimeError: [enforce fail at alloc_cpu.cpp:80] data. DefaultCPUAllocator: not enough memory

### ISSUE THREAD

**Issue by kenic123** [ManglerFTW/ComfyI2I#20]
Error occurred when executing Inpaint Segments:

[enforce fail at alloc_cpu.cpp:80] data. DefaultCPUAllocator: not enough memory: you tried to allocate 82463372083200 bytes.

后台报错信息：

Prompt executed in 1.06 seconds
got prompt
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "E:\ComfyUI_Pro\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "E:\ComfyUI_Pro\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "E:\ComfyUI_Pro\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "E:\ComfyUI_Pro\ComfyUI\custom_nodes\ComfyI2I\ComfyI2I.py", line 1430, in get_region
    Cut_Image = CutByMask(image, region, force_resize_width, force_resize_height, mask_mapping_optional)
  File "E:\ComfyUI_Pro\ComfyUI\custom_nodes\ComfyI2I\ComfyI2I.py", line 623, in CutByMask
    image = image[mask_mapping_optional]
RuntimeError: [enforce fail at alloc_cpu.cpp:80] data. DefaultCPUAllocator: not enough memory: you tried to allocate 82463372083200 bytes.

Prompt executed in 0.34 seconds
got prompt
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "E:\ComfyUI_Pro\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "E:\ComfyUI_Pro\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "E:\ComfyUI_Pro\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "E:\ComfyUI_Pro\ComfyUI\custom_nodes\ComfyI2I\ComfyI2I.py", line 1430, in get_region
    Cut_Image = CutByMask(image, region, force_resize_width, force_resize_height, mask_mapping_optional)
  File "E:\ComfyUI_Pro\ComfyUI\custom_nodes\ComfyI2I\ComfyI2I.py", line 623, in CutByMask
    image = image[mask_mapping_optional]
RuntimeError: [enforce fail at alloc_cpu.cpp:80] data. DefaultCPUAllocator: not enough memory: you tried to allocate 82463372083200 bytes.

**Comment by rollingcookies** [comment]
Same problem! 
![image](https://github.com/ManglerFTW/ComfyI2I/assets/40675630/44ed789f-7af5-4d03-a9ca-843eeadec932)
